### ISSUE TITLE
Wrong Error message.

### ISSUE THREAD

**Issue by adamshamsudeen** [sunscrapers/djoser#271] opened 2018-03-20 15:24 UTC
I'm getting the same error message when the credentials are invalid and when the account is not active. I don't understand why the INACTIVE_ACCOUNT_ERROR is not being raised.

``
curl -X POST http://127.0.0.1:8000/auth/token/create/ --data 'email=adam@gmail.com&password=nottherealone'
{"auth_token":"11c05aade9a77656794d70c4bcea8cc4d57d29df"}
 ``

After deactivating:

`
curl -X POST http://127.0.0.1:8000/auth/token/create/ --data 'email=adam@gmail.com&password=nottherealone'
{"non_field_errors":["Unable to login with provided credentials."]}
`

I'm using email as the USERNAME_FIELD.

Thanks

**Comment by adamshamsudeen** [comment] 2018-03-21 10:15
Found this answer from stackoverflow:
The default ModelBackend authentication backend started rejecting inactive users in Django 1.10. Therefore your authenticate() call returns None, and you get the Invalid username/password! message from the outer if/else statement.
If you use the default ModelBackend, you no longer need to check user.is_active in your login view.

If you really want authenticate to return inactive users, then you can use AllowAllUsersModelBackend instead. If you do this, then it is your responsibility to check the is_active flag in your login view.

Solved by adding authentication Backend:

``
AUTHENTICATION_BACKENDS = ['django.contrib.auth.backends.AllowAllUsersModelBackend']
``

**Comment by zefciu** [comment] 2019-01-18 12:45
Duplicate of https://github.com/sunscrapers/djoser/issues/279

**Closed by zefciu** 2019-01-18 12:45 UTC

**Comment by Srivastav-Java-Coder** [comment] 2023-03-09 15:36
@adamshamsudeen Hi adam can you please tell about AUTHENTICATION_BACKENDS = ['django.contrib.auth.backends.AllowAllUsersModelBackend'] where exactly need to paste this?
