### ISSUE TITLE
Custom User + USERNAME_FIELD

### ISSUE THREAD

**Issue by borbotonc** [sunscrapers/djoser#264] opened 2018-02-07 19:06 UTC
When you create a custom user with email as USERNAME_FIELD, the serializer considers it a a read only field, so when you want to document the API it will not show it as a required field.

<img width="366" alt="screen shot 2018-02-07 at 4 05 37 pm" src="https://user-images.githubusercontent.com/36242460/35936009-cdeb1d40-0c20-11e8-91c0-693b8313afa1.png">

**Comment by zefciu** [comment] 2019-01-22 10:04
Hello! I created an application with a custom user model using the email field as username. I have generated the documentation using the drf tools. There is an e-mail field documented as required on creating a user. Could you clarify what tool are you using and how does your model look like? I'm closing for now. If the problem is still reproducible, please reopen.

**Closed by zefciu** 2019-01-22 10:04 UTC
