### ISSUE TITLE
Add JSON Web Token authentication support

### ISSUE THREAD

**Issue by haxoza** [sunscrapers/djoser#40] opened 2015-04-26 22:41 UTC
It would great to support the following project that implements JWT auth backend: https://github.com/GetBlimp/django-rest-framework-jwt

**Comment by konradhalas** [comment] 2015-04-27 09:02
+1 Any ideas how we could support DRF token, our custom multi device token and JWT? Probably we should implement some generic layer between our views and authentication backends.

**Comment by avimeir** [comment] 2015-04-27 09:42
I'm already using djoser with DRF-JWT and it seems to be working just fine. Is it a weird unexpected feature?

**Comment by haxoza** [comment] 2015-04-27 09:47
Sounds awesome! It would be cool to have it documented and tested. @avimeir, we will appreciate any pull requests in that matter!

**Comment by avimeir** [comment] 2015-04-27 09:52
Try to turn on token-based authentication on DRF (http://www.django-rest-framework.org/api-guide/authentication/#tokenauthentication) and then follow the usual install of DRF-JWT, then added djoser and it works right of the box with no modifications to the code.

**Comment by NabeelValapra** [comment] 2015-04-29 09:40
@avimeir, 
1. If so still djoser will be creating token in the database? how did you overcame it?
2. Will be there any change in the flow of /login/,?

**Comment by avimeir** [comment] 2015-04-29 12:10
@NabeelValapra 
1. I assume that djoser will use the authentication class configured by DRF, which happens to be DRF-JWT (rest_framework_jwt.authentication.JSONWebTokenAuthentication). I must admit that I haven't looked into it, so the fact that it's working is pure magic at this point :)
2. Well, you need to follow the DRF-JWT flow for issuing a JWT, by default the endpoint is: ^api-token-auth/

**Comment by liaoliaopro** [comment] 2015-05-08 03:10
+1 to support JWT. make authentication backend configurable instead of binding with Token auth.

**Comment by avances123** [comment] 2015-05-19 13:34
I have read the @haxoza POC in this matter and I think is the way to do it, by the way:

@NabeelValapra 
1.  You use rest_framework_jwt.authentication.JSONWebTokenAuthentication, and delete 'rest_framework.authtoken' from your installed apps. At this point, /auth/login/ endpoint is broken (maybe some others) as the token table is not created
2. I override djoser login url with drf-jwt 
```
url(r'^auth/login/', 'rest_framework_jwt.views.obtain_jwt_token'),
```

**Comment by cerdman** [comment] 2016-06-21 22:23
+1

**Comment by uniqueg** [comment] 2016-09-09 08:02
What is the status here? Did anyone get it to work, reproducibly? Would be much appreciated...

**Comment by konradhalas** [comment] 2016-09-09 08:45
Hi @uniqueg, you can always try something like this:

```python

import rest_framework_jwt.views
import djoser.views

urlpatterns = [
    url(r'^auth/login', rest_framework_jwt.views.obtain_jwt_token),
    url(r'^auth/register', djoser.views.RegistrationView.as_view()),
    url(r'^auth/password/reset', djoser.views.PasswordRestView.as_view()),
    url(r'^auth/password/confirm', djoser.views.PasswordResetConfirmView.as_view()),
    ...
]
```

To be honest, I think that we don't have to implement anything in `djoser` to support JWT right now.

@haxoza maybe we should close this issue?

**Comment by lwm** [comment] 2016-09-09 08:50
@konradhalas 

Please document your answer somewhere before closing? 

But I agree. It just works.

**Comment by uniqueg** [comment] 2016-09-09 13:10
Thanks a lot @konradhalas and @lwm, it sounds straightforward enough, and clean too! I was a bit confused by the previous discussion and wasn't sure it would work.

**Closed** 2016-09-25 19:23 UTC
Labels: enhancement

**Comment by lwm** [comment] 2016-09-25 19:33
FYI: https://github.com/sunscrapers/djoser#json-web-token-authentication
