### ISSUE TITLE
djoser.readthedocs.io not up-to-date

### ISSUE THREAD

**Issue by nils-wisiol** [sunscrapers/djoser#309] opened 2018-09-20 13:12 UTC
"Latest" documentation on djoser.readthedocs.io is not 1.3.0, but some different version. Specifically, `SERIALIZERS.current_user` is missing from the settings documentation.

Compare:
[Outdated documentation on readthedocs](https://djoser.readthedocs.io/en/latest/settings.html)
[Should-be documentation on github](https://github.com/sunscrapers/djoser/blob/master/docs/source/settings.rst)
(CTRL-F "current_user")

**Comment by joshua-s** [comment] 2018-09-25 16:14
@dekoza can we set up auto build?

**Comment by dekoza** [comment] 2018-11-12 11:53
The autobuild need to be switched to `master` from rather obscure `version-1.x` branch.

**Comment by peterkmurphy** [comment] 2019-01-23 01:52
We're in 2019, and the issue is getting serious. We now have some breaking changes in the jwt support. 1.3.2 and before, djoser used rest_framework_jwt; now (1.4.0) it uses rest_framework_simplejwt. The API has changed as a result. I need some easy way to migrate between the two. 

If someone could sort it, I would be grateful. Thank you very much.

**Comment by peterkmurphy** [comment] 2019-01-23 07:18
I was able to migrate from 1.3.2 to 1.4.0 (and from  rest_framework_jwt to rest_framework_simplejwt), but it wasn't a pleasant couple of hours. My notes for the documentation, so as to save anyone else pain.

1. POST to /v0/jwt/create with username and password. Before, the server returns JSON with one key "token" match a value (the JWT). In 1.4.0, the server returns two keys. There's "access", and its value is the JWT; it's basically a replacement for "token". There's also "refresh", and its value is used for refreshing tokens.
2. In 1.3.2, the value for "token" can be used with POSTs to /v0/jwt/verify and  /v0/jwt/refresh. In 1.4.0, the value for "access" is used for the verify URL (and for other places where you use JWT). But the value for "refresh" is used with  /v0/jwt/refresh instead.
3. When you are using rest_framework_jwt, you pass HTTP headers like:

`Authorization: JWT <token>` 

The rest_framework_simplejwt expects headers like:

`Authorization: Bearer <token>`

Does that mean a rewrite of the code using your API ? Not necessarily; put something like this in your settings.py file

```
SIMPLE_JWT = {
    "AUTH_HEADER_TYPES": ("Bearer", "JWT"),
} 
```

I hope this information is of use for the document writers. Cheers.

**Comment by joshua-s** [comment] 2019-01-23 07:32
Thank you @peterkmurphy. I am planning to create a PR to add this to the docs. I can't publish them on RTD, though.

**Comment by joshua-s** [comment] 2019-01-29 21:36
I added the new docs in #347

**Comment by joshua-s** [comment] 2019-02-08 15:01
New docs have been merged. Can someone switch the autobuild to master so that they will appear on RTD? @zefciu @dekoza

**Comment by dekoza** [comment] 2019-02-09 07:07
I'm on it. We needed to regain the access to readthedocs from previous dev.

**Closed** 2019-05-24 13:45 UTC
